# Generated by Django 5.0.1 on 2024-02-09 17:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('p_id', models.IntegerField(default=api.models.get_id, unique=True)),
                ('p_name', models.CharField(max_length=50)),
                ('p_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(default=api.models.get_id, unique=True)),
                ('username', models.CharField(max_length=15)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
