# Generated by Django 5.0.1 on 2024-02-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='array',
            field=models.JSONField(),
        ),
    ]
