# Generated by Django 5.0.1 on 2024-02-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_test_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='array',
            field=models.TextField(),
        ),
    ]
