# Generated by Django 5.0.1 on 2024-02-14 20:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_graphdatabase_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdatabase',
            name='date',
            field=models.DateField(default=api.models.get_current_date),
        ),
    ]
