# Generated by Django 5.0.1 on 2024-02-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_graphdatabase_total_vloume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphdatabase',
            old_name='total_vloume',
            new_name='total_volume',
        ),
    ]
